<?php
/******************************************************************************
 *
 * Purpose: title
 * Author:  Salvatore Larosa
 *
 ******************************************************************************/

// includes php
include_once ("incphp/layout.php");

function isMobile() {
	return preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", $_SERVER["HTTP_USER_AGENT"]);
}
?>
<!--<!doctype html>-->
<!DOCTYPE HTML>
<html>
	<head>
		<title>#rifiutocivico, contro una città indifferenziata.</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="mobile-web-app-capable" content="yes">
		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		<!-- <meta name="viewport" content="width=device-width, initial-scale=1" /> -->
		<!-- <meta property="og:image" content="route.png" /> -->
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<!-- <link rel="stylesheet" href="//unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css"/> -->
		<link rel="stylesheet" href="css/layout-default-latest.css" />
		<!-- <link rel="stylesheet" href="css/jquery-ui-1.8.14.custom.css" /> -->
		<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
		<!-- <link rel="stylesheet" href="css/index.css" /> -->
		<link rel="stylesheet" href="lib/leaflet/leaflet.css" />
		<!-- <link rel="stylesheet" href="css/leaflet.zoomhome.css" /> -->
		<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.css"> -->
		<!-- <link type="text/css" rel="stylesheet" href="css/table-populator.css"/> -->
		<link type="text/css" rel="stylesheet" href="css/jquery.dataTables.min.css"/>
		<!-- <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-rc.2/dist/leaflet.css"/> -->
		<link rel="stylesheet" href="css/Leaflet.Coordinates-0.1.5.css"/>
		<link rel="stylesheet" type="text/css" href="css/L.VisualClick.css" />
		<!-- <link rel="stylesheet" type="text/css" href="css/Leaflet.NavBar.css" /> -->
		<!-- <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" /> -->
		<!-- <link rel="stylesheet" href="https://unpkg.com/leaflet@1.1.0/dist/leaflet.css" /> -->
		<link rel="stylesheet" href="lib/cluster/MarkerCluster.css" />
		<link rel="stylesheet" href="lib/Leaflet.Photo.css" />

		<link rel="stylesheet" href="css/map.css" />
		<link rel="stylesheet" href="css/leaflet-sidebar.css" />
		<link rel="stylesheet" href="css/leaflet-search.css" />
		<!-- <link rel="stylesheet" href="css/leaflet-search.mobile.css" /> -->

		<style>
			body {
				padding: 0;
				margin: 0;
			}

			html, body, #map {
				height: 100%;
				font: 10pt "Helvetica Neue", Arial, Helvetica, sans-serif;
			}

			.lorem {
				font-style: italic;
				color: #AAA;
			}

			.centered {
				display: inline-block;
				height: 100%;
				vertical-align: middle;
			}

			.ui-layout-north, .ui-layout-south, .ui-layout-resizer {
				background-color: #fff;
				/*background-image: url("https://farm5.staticflickr.com/4291/35349802304_66a3f43b6f_o.jpg");
				 background-position: 100% 100%;
				 background-repeat: no-repeat;*/
				border: medium none;
				color: #000;
			}
			.ui-layout-south {
				/*background-color: #000;*/
				padding: 0;
			}
			.ui-layout-center {
				overflow: hidden;
				padding: 0;
			}
			.ui-layout-west {
				/*overflow: hidden;*/
				padding: 0;
			}
			.ui-layout-pane {
				overflow: hidden;
				border: 0px;
			}
			.heading {
				position: absolute;
				color: #000;
				font-size: 30px;
				padding: 10px;
				/*font-weight: bold;*/
				text-align: left;
				margin-top: -12px;
			}
			.heading_mobile {
				position: absolute;
				color: #000;
				font-size: 30px;
				padding: 10px;
				/*font-weight: bold;*/
				text-align: left;
				margin-top: -10px;
			}
			/* Smartphones ----------- */
			@media only screen and (max-width: 760px) {
				#some-element {
					display: none;
				}
			}
		</style>
		<script type="text/javascript" src="js/jquery-latest.js"></script>
		<script type="text/javascript" src="js/jquery.layout-latest.js"></script>
		<!-- <script src="js/jquery-ui-1.8.4.custom.min.js" type="text/javascript"></script> -->
		<script src="http://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="js/jquery.accordion.js" type="text/javascript"></script>

		<!-- <script src="http://code.jquery.com/jquery-migrate-1.0.0.js"></script> -->
		<script type="text/javascript" src="js/jquery.dataTables.min.js"></script>

		<script src="lib/reqwest.min.js"></script>

		<!-- <script src="js/leaflet.zoomhome.js"></script> -->
		<!-- <script src="js/Leaflet.NavBar.js"></script> -->
		<!-- <script src="js/index.js"></script> -->
		<script type="text/javascript">
			$(document).ready(function() {
				$('body').layout({
					// west__size: 0,
					// west__resizable: false
					north__size : 60,
					south__size : 0,
					west__size : 0,
					north__spacing_open : 0,
					south__spacing_open : 0,
					west__spacing_open : 0
				});
				var table = $('#example').DataTable({
					// "processing": true,
					// "serverSide": true,
					"ajax" : {
						"url" : "data.json",
						"dataSrc" : ""
					},
					// "sAjaxSource": "data.json",
					// "bProcessing": true,
					// "sAjaxDataProp":"data",
					// "bServerSide": true,
					"columns" : [{
						"data" : "url_t",
						"render" : function(data, type, row) {
							return '<img src="' + data + '" />';
						}
					}, {
						"data" : "title"
					}, {
						"data" : "ispublic",
						"render" : function(data, type, row) {
							return '<a href="http://maps.google.com/maps?f=d&hl=it&daddr=' + row.latitude + ',' + row.longitude + '&ie=UTF8&0&om=0&output=kml" target="_blank">' + '<img width="32px" src="images/google-maps.png" /></a>'
						}
					}],
					"language" : {
						"lengthMenu" : "Mostra _MENU_ righe per pagina",
						"search" : "Cerca:",
						"zeroRecords" : "Nessuna voce trovata.",
						"info" : "Pagina _PAGE_ di _PAGES_",
						"infoEmpty" : "Nessun dato disponibile",
						"infoFiltered" : "(filtro applicato a _MAX_ righe in totale)",
						"paginate" : {
							"first" : "First",
							"last" : "Last",
							"next" : "Succ.",
							"previous" : "Prec."
						}
					}
				});
				$('#example tbody').on('click', 'tr', function() {
					var data = table.row(this).data();
					// console.log(data.latitude);
					// map.panTo(new L.LatLng(data.latitude, data.longitude));
					map.setView([data.latitude, data.longitude], 18);
					// alert('You clicked on ' + data + '\'s row');
				});
			});
		</script>
	</head>
	<body>
		<div class="ui-layout-center">
			<?php
			if (!isMobile())
				echo Ui::sidebar();
 ?>
			<div id="map" class="sidebar-map"></div>
			<script src="lib/leaflet/leaflet.js"></script>
			<!-- <script src='js/leaflet.zoomhome.js'></script> -->
			<!-- <script src="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.js"></script> -->
			<script src="js/leaflet-ajax.js"></script>
			<script src="js/leaflet-search.js"></script>
			<!-- <script type="text/javascript" src="js/table-populator.js"></script> -->

			<!-- <script src="https://unpkg.com/leaflet@1.0.0-rc.2/dist/leaflet.js"></script> -->
			<script src='https://xguaita.github.io/mtig-js/libs/leaflet-providers.js'></script>
			
			<script src="js/leaflet-sidebar.js"></script>
			<script src="lib/cluster/leaflet.markercluster.js"></script>
			<script src="lib/Leaflet.Photo.js"></script>
			<script type="text/javascript" src="js/Leaflet.Coordinates-0.1.5.src.js"></script>
			<script src="js/L.VisualClick.js"></script>
			<!-- <script src="comuni.js"></script> -->
			<script src="js/index.js" type="text/javascript"></script>
		</div>
		<div class="ui-layout-west">
			<?php //echo Ui::westElement() ?>
		</div>
		<div class="ui-layout-north">
			<?php echo Ui::headerElement() ?>
		</div>

		<div class="ui-layout-south">
			<?php //echo Ui::footerElement() ?>
		</div>
	</body>
</html>